{
 "title": "P1 Homewizard",
 "tags": [
  "gohome",
  "p1_homewizard"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Scrape status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gohome_p1_homewizard_scrape_success"
    }
   ]
  },
  {
   "title": "Current power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gohome_p1_homewizard_active_power_w"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gohome_p1_homewizard_import_power_w - gohome_p1_homewizard_export_power_w"
    }
   ]
  },
  {
   "title": "Consumed (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gohome_p1_homewizard_total_import_kwh[24h])"
    }
   ]
  },
  {
   "title": "Produced (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gohome_p1_homewizard_total_export_kwh[24h])"
    }
   ]
  },
  {
   "title": "Cost (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(gohome_p1_homewizard_total_import_t1_kwh[24h]) * gohome_p1_homewizard_tariff_import_t1_eur_per_kwh) + (increase(gohome_p1_homewizard_total_import_t2_kwh[24h]) * gohome_p1_homewizard_tariff_import_t2_eur_per_kwh) - (increase(gohome_p1_homewizard_total_export_t1_kwh[24h]) * abs(gohome_p1_homewizard_tariff_export_t1_eur_per_kwh)) - (increase(gohome_p1_homewizard_total_export_t2_kwh[24h]) * abs(gohome_p1_homewizard_tariff_export_t2_eur_per_kwh))"
    }
   ]
  },
  {
   "title": "Energy flow (24h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwh" } },
   "targets": [
    {
     "expr": "increase(gohome_p1_homewizard_total_import_kwh[$__rate_interval])",
     "legendFormat": "Consumed"
    },
    {
     "expr": "-1 * increase(gohome_p1_homewizard_total_export_kwh[$__rate_interval])",
     "legendFormat": "Produced"
    }
   ]
  }
 ]
}